# Generated by Django 3.1.5 on 2024-06-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20210712_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
